[custom.all.missing-containers]
type = "local"
path = "."
ipkg = "missing-containers.ipkg"
test = "test/test.ipkg"

[custom.all.missing-containers-test]
type = "local"
path = "test"
ipkg = "test.ipkg"