name: AnyCommit
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - $default-branch

env:
  SCHEME: scheme
  IDRIS2_CFLAGS: -O2

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CC: gcc
      PACK_DIR: /root/.pack
    container: ghcr.io/stefan-hoeck/idris2-pack:latest    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: apt-get dependencies
        run: |
          apt-get update
          apt-get install -y clang-14 clang-15 gcc

      - name: Checkout
        uses: actions/checkout@v3

      - run: idris2 --version
      - run: pack install-deps missing-containers
      - run: pack build missing-containers
      - run: pack --cg=chez test  missing-containers
      - run: IDRIS2_CC=gcc pack --cg=refc test  missing-containers
      - run: IDRIS2_CC=clang-14 pack --cg=refc test  missing-containers
      - run: IDRIS2_CC=clang-15 pack --cg=refc test  missing-containers
      - run: pack --cg=node test  missing-containers

      - run: pack install missing-containers

